# Generated by Django 5.0.1 on 2024-01-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="create_at", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user", old_name="update_at", new_name="updated_at",
        ),
    ]
